export const FETCH_TASKS = 'tasks/FETCH'
export const WATCH_TASKS = 'tasks/WATCH'
export const UPDATE_TASK = 'tasks/UPDATE'
export const ADD_TASK = 'tasks/ADD'
export const DELETE_TASK = 'tasks/DELETE'
export const COMPLETE_TASK = 'tasks/COMPLETE'
