apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: todo
        version: v1
        visualize: "true"
      name: todo-service
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 80
          targetPort: 3000
      type: LoadBalancer
      selector:
        app: todo
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: todo
        version: v1
        visualize: "true"
      name: todo-rc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: todo
          version: v1
      template:
        metadata:
          labels:
            visualize: "true"
            app: todo
            version: v1
        spec:
          containers:
          - image: jbclaramonte/todomvc-redux-rethinkdb:rethinkdb-arm
            name: todo
            imagePullPolicy: Always
            env:
            - name: REPLICAS
              value: "3"
            ports:
            - containerPort: 3000
              name: web
