apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-persistence-disk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: rethinkdb-disk
    fsType: ext4
